let num1 = 50;
let num2 = 40;

console.log("============OUTPUT============");
console.log("First Number  "+num1);
console.log("Second Number "+num2);
console.log("=============INPUT============");
if ( num1 > num2 ){
    console.log("First number is greater");
} else if ( num2 > num1){
    console.log("Second number is greater ");
} else if ( num1 = num2 ) {
    console.log("Both numbers are equal");
}
console.log("===============================");